### ISSUE TITLE
Add gradle support

### ISSUE THREAD

**Issue by kenumir** [borax12/MaterialDateRangePicker#1]
Add gradle/maven support for faster include in projects

**Comment by heysupratim** [comment]
its coming they say . coming so very soon

**Comment by xingag** [comment]
Add more custom attributes

**Comment by heysupratim** [comment]
Gradle Support is now present in version 1.1 check the readme

**Comment by Harti** [comment]
I'm getting:

```
Error:(40, 13) Failed to resolve: com.borax12.materialdaterangepicker:library:1.1
```

build.gradle:

```

repositories {
    jcenter()
    maven { url "https://clojars.org/repo/" }
}
dependencies {
    ...
    compile 'com.borax12.materialdaterangepicker:library:1.1'
}
```

Is the namespace incorrect? 
Earlier it told me something about erroneous metadata (and something about it found "material-datetime-picker" instead of "library" - but putting the former didn't work either).

**Comment by heysupratim** [comment]
Hey - issue is fixed - write this as the group id and artificact id - compile 'com.borax12.materialdaterangepicker:library:1.2'

**Comment by Harti** [comment]
Thanks, Gradle inclusion works perfectly now!
Thank you for the very swift reply and for making this library.
