### ISSUE TITLE
Library Conflicts With AndroidX Libraries

### ISSUE THREAD

**Issue by napperley** [borax12/MaterialDateRangePicker#100]
When running the **app** task in Android Studio a error appears at the **Run tasks** stage:

```
Error: Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
```

Appears as though the MaterialDateRangePicker library is having conflicts with the AndroidX libraries. The MaterialDateRangePicker library shouldn't be registering the **android.support.v4.app.INotificationSideChannel** program type.

**Comment by clunyes** [comment]
> When running the **app** task in Android Studio a error appears at the **Run tasks** stage:
> 
> ```
> Error: Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
> ```
> Appears as though the MaterialDateRangePicker library is having conflicts with the AndroidX libraries. The MaterialDateRangePicker library shouldn't be registering the **android.support.v4.app.INotificationSideChannel** program type.

how you find this conflict?

**Comment by pavelpoley** [comment]
How to solve this issue?
`dpd.show(.getSupportFragmentManager(), "Datepickerdialog");`

> Cannot resolve method show(androidx.fragment.app.FragmentManager, ... )

**Comment by heysupratim** [comment]
This is fixed in the upcoming release. To see how it might work, please use the lastest code snapshot in the master branch
