### ISSUE TITLE
I want to use this library in an androidx project

### ISSUE THREAD

**Issue by pierrekhouryy** [borax12/MaterialDateRangePicker#106]
HI,
I recently migrated my project to androidx, so everytime I try to show the dialog I have to pass a fragment manager from the android package, however the method .show() in the library requires an appcompat fragment manager. Is there a way around this or is impossible to use this library in an androidx project?
thanks, 
Pierre

**Comment by tomscholz** [comment]
Related to #105 :)

**Comment by heysupratim** [comment]
Closing this issue as rightly pointed out by @tomscholz, it is an elaboration of issue #105. Tracking updates there
