### ISSUE TITLE
Change HEADER["FROM" "TO"] 

### ISSUE THREAD

**Issue by figus1909** [borax12/MaterialDateRangePicker#14]
I need to change the "FROM" and "TO" strings on top of DatePicker, such that I am using multilanguage app. Which string I have to define in strings.xml file in order to change this headers.

**Comment by heysupratim** [comment]
i am going to release the new version which will have the setTitle and setEndTitle method . as of now , check the code for tabhost.setIndicator("start") and tabhost.setIndicator("end")  to change the strings .

**Comment by figus1909** [comment]
Could you please explain briefly what should I do in order to change
strings ? Sorry I new to android -(
25 янв. 2016 г. 13:58 пользователь "Supratim Chakraborty" <
notifications@github.com> написал:

**Comment by heysupratim** [comment]
@figus1909 - i updated the new version , 1.4. Use that library function setStartTitle and setEndTitle

**Comment by figus1909** [comment]
Now App crashes , if I comment setTitle and setEndTitle lines everything works ok, hovewer when I used them it compiles without no problem , but on opening of DatePickerDialog crashes.

**Comment by figus1909** [comment]
My Main Activity is

package com.huseyn.mytestservice.app.activities;

import android.app.DatePickerDialog;
import android.app.Dialog;
import android.app.ProgressDialog;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.Button;

import android.widget.DatePicker;
import android.widget.ProgressBar;
import android.widget.Toast;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.huseyn.mytestservice.app.R;

import com.huseyn.mytestservice.app.adapters.MyRecycleViewAdapter;
import com.huseyn.mytestservice.app.pojo.MyMap;
import com.huseyn.mytestservice.app.service.MyRetrofit;
import com.huseyn.mytestservice.app.service.WeatherService;
import com.squareup.okhttp.OkHttpClient;
import retrofit.*;

import java.io.IOException;
import java.util.*;

/**
- Created by HGPashayev on 1/21/2016.
  */
  public class Main_Activity extends AppCompatActivity {
  
  private Button datePicker;
  
  private int year,month,day,eyear,emonth,eday;
  
  @Override
  
  protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      setContentView(R.layout.main_layout);
      Calendar c = Calendar.getInstance();
      year=c.get(Calendar.YEAR);
      month=c.get(Calendar.MONTH);
      day=c.get(Calendar.DAY_OF_MONTH);
  
  ```
  showDate();
  ```
  
  }
  com.borax12.materialdaterangepicker.date.DatePickerDialog.OnDateSetListener listener = new com.borax12.materialdaterangepicker.date.DatePickerDialog.OnDateSetListener() {
      @Override
      public void onDateSet(com.borax12.materialdaterangepicker.date.DatePickerDialog datePickerDialog, int i, int i1, int i2, int i3, int i4, int i5)
      {
          year=i;
          month=i1;
          day=i2;
          eyear=i3;
          emonth=i4;
          eday=i5;
          Toast.makeText(Main_Activity.this,"Start Date:"+day+"/"+month+"/"+year+"End date: "+eday+"/"+emonth+"/"+eyear,Toast.LENGTH_SHORT).show();
      }
  };
  
  public void showDate()
  {
      datePicker =(Button)findViewById(R.id.datePickerButton);
      datePicker.setOnClickListener(new View.OnClickListener() {
          @Override
          public void onClick(View view)
          {
              com.borax12.materialdaterangepicker.date.DatePickerDialog dp = com.borax12.materialdaterangepicker.date.DatePickerDialog.newInstance(listener,year,month,day);
              dp.setStartTitle("Start date");
              dp.setEndTitle("End date");
              dp.show(getFragmentManager(), "MyDatePciker");
  
  ```
      }
  });
  ```
  
  }

}

Logcat

java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.TabHost$TabSpec android.widget.TabHost.newTabSpec(java.lang.String)' on a null object reference
            at com.borax12.materialdaterangepicker.date.DatePickerDialog.setStartTitle(DatePickerDialog.java:906)
            at com.huseyn.mytestservice.app.activities.Main_Activity$3.onClick(Main_Activity.java:146)
            at android.view.View.performClick(View.java:5226)
            at android.view.View$PerformClick.run(View.java:21266)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:168)
            at android.app.ActivityThread.main(ActivityThread.java:5845)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
01-25 14:54:42.828  13865-13865/com.huseyn.mytestservice.app D/Process﹕ killProcess, pid=13865
01-25 14:54:42.830  13865-13865/com.huseyn.mytestservice.app D/Process﹕ com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:113 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690

**Comment by heysupratim** [comment]
@figus1909 - hey i had accepted somebodys pull request without reviewing it , and it was a wrong code, fixed it and released 1.5. Please look at it now :) Also i will be overhauling this library very soon to be more customizable , so keep an eye out for it :)

**Comment by figus1909** [comment]
Great work !!! Thank you a lot !

**Comment by mengmengmengmeng** [comment]
Hi! is this also applicable on timepicker's header? thanks!
