### ISSUE TITLE
Can't select end date month different from start date month

### ISSUE THREAD

**Issue by figus1909** [borax12/MaterialDateRangePicker#15]
Hello I found new bug when I select start date month and then want to select end date month which is different from selected start date month , it selects but it returns you in same month which was selected on start date.

**Comment by heysupratim** [comment]
@figus1909 - Can you elaborate more, i am trying to replicate it , it isnt happening on my end

**Comment by figus1909** [comment]
for Example on From tab select January 20 2016, then go to To tab and select month different from January - for example select June 30 2016 , you will see that even if you select the 30 JUNE 2016 the calendar view will return to january 2016 view , however if you will scroll to 30 JUNE you will see that date selected , just after you press it it return you to January 2016 month(The month selected in FROm tab)

**Comment by heysupratim** [comment]
Ah i got that , well give me some time , will fix it tonight , by the time if you do get time to look at the code , feel free to give a PR for the same

**Comment by figus1909** [comment]
ok, I am waiting for fix :) I think in issue "Date picker To jump back after click on day #6" have the same issue.

**Comment by figus1909** [comment]
Dear Borax12 were you able to fix the bug ? :/

**Comment by heysupratim** [comment]
@figus1909 - fixed check in version 1.6

**Comment by figus1909** [comment]
Error:(47, 13)  Failed to resolve: com.borax12.materialdaterangepicker:library:1.6

**Comment by heysupratim** [comment]
go to project and clear cache / and do a project clean

**Comment by figus1909** [comment]
Do I need to change version from 1.5 to 1.6 in build.gradle ?
28 янв. 2016 г. 14:29 пользователь "Supratim Chakraborty" <
notifications@github.com> написал:

**Comment by heysupratim** [comment]
yeah and do a gradle sync and project clean

**Comment by figus1909** [comment]
compile 'com.borax12.materialdaterangepicker:library:1.6' I added this dependency in gradle , and done clean project again  got this error

**Comment by figus1909** [comment]
Also as I can see the gradle dependency didn't updated in gitPage maybe this is somehow related :/ sorry I am newbie

**Comment by heysupratim** [comment]
do one thing, remove the dependency and then do a gradle sync and then add it again

**Comment by figus1909** [comment]
Checked didn't work, again same error I also tried writing the version 1.4, 1.3, 1.2 it synced without no problem but while writing 1.6 it gives this error

**Comment by heysupratim** [comment]
can you reach this url - http://jcenter.bintray.com/com/borax12/materialdaterangepicker/library/
also you do have jcenter() added in the repository info right ?

**Comment by figus1909** [comment]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.1'
    }
}
apply plugin: 'com.android.application'

repositories {
    jcenter()
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    applicationId "com.huseyn.internetbanking.app"
    minSdkVersion 14
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_6
    targetCompatibility JavaVersion.VERSION_1_6
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.squareup.retrofit:retrofit:2.0.0-beta2'
    compile 'com.squareup.retrofit:converter-gson:2.0.0-beta2'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.android.support:cardview-v7:23.1.0'
    compile 'com.android.support:recyclerview-v7:23.1.0'
    compile 'com.borax12.materialdaterangepicker:library:1.6'

}

this is my Gradle build file
yes I can reach this URL

**Comment by heysupratim** [comment]
I tried in some other new project and it worked for me. can you try it in a fresh project?

**Comment by figus1909** [comment]
Dear Borax12 sorry I think I am facing proxy problem on my PC now, such that I gave another dependency it also wasn;t able to resolve I will try to solve and let you know , thanks for your efforts!

**Comment by heysupratim** [comment]
:+1: no probelm @figus1909 - just update me here if find the problem

**Comment by figus1909** [comment]
I have solved the problem , before today I was using ItelijIdea for Android projects, and today shifted to Android Studio because of rendering problems on IntelijIdea , the proxy was configured on Itelij however there it also was configured but with incorrect credentials )) my fauld just passed mistakenly wrong password, that why was facing sync problem )) Thanks for your efforts and patience!

**Comment by heysupratim** [comment]
Ah thats what i was wondering. The sync issue should not occur if it was
working on all new  Projects I tried.

Anyways keep using the library and spread the word about it. Also if you
think a new feature can be added and you can contribute. Go ahead and send
a pr

**Comment by figus1909** [comment]
I will try , I am newbie in Android so have some problems , for now I am locally added the feature which checks that end date is greater than start date , if false case Toast popup and says that wrong interval and DateRangePicker popus again ))) this is my upgrade ))

**Comment by heysupratim** [comment]
Hey no issues man, that is a good start. Keep building and the force will be with you :)
