### ISSUE TITLE
Initialize DateRangePicker with end date

### ISSUE THREAD

**Issue by paralen** [borax12/MaterialDateRangePicker#16]
It is possible to initialize DateRangePicker with a custom end date? It would be nice if we could set arbitrary start and end date.

**Comment by heysupratim** [comment]
@paralen -  i will be definitely looking into this . There is so much going , maintenance becomes tough, if at all you do end up making that feature. Do submit a PR. I will review it

**Comment by csbenz** [comment]
See #17

**Comment by heysupratim** [comment]
@paralen @csbenz  - merging the PR :)
