### ISSUE TITLE
Use the original library by wdullaer

### ISSUE THREAD

**Issue by Lecraver** [borax12/MaterialDateRangePicker#21]
I am interested in using your library but also by the original, is it possible to use both ?
I have this when I add the second library :

```
java.lang.ClassCastException: com.wdullaer.materialdatetimepicker.date.AccessibleDateAnimator cannot be cast to com.borax12.materialdaterangepicker.date.AccessibleDateAnimator
```

In my gradle :

```
    compile 'com.wdullaer:materialdatetimepicker:2.1.1'
    compile 'com.borax12.materialdaterangepicker:library:1.5'
```

Is it possible not to use the from-to in MaterialDateRangePicker ?

Best regards,

**Comment by heysupratim** [comment]
I will be adding the regular singular date and time pickers too . so i think that will remove the need to use both the libs :)
