### ISSUE TITLE
Only one option, instead of From & To

### ISSUE THREAD

**Issue by ghost** [borax12/MaterialDateRangePicker#26]
Is there a way to only enable one option dialog, no two (From & To). I know the whole point of this library is that it is a range picker, but it's probably worth asking.

I need a range picker for date, but only single picker for time. My options are to use android picker for time, but I want it to look the same for older versions of Android.

**Comment by heysupratim** [comment]
@skmlcd  you will have to disable the tabhost second tab . Why dont you help add these feature . Seems like an easy code . I am working on other things , so i would be glad if you could help me add the feature.

**Comment by ghost** [comment]
You're right. Maybe I can write that code and submit a pull request, no promises though.

**Comment by heysupratim** [comment]
Thanks. No hurry

**Comment by mafujuls** [comment]
hey, Have you fix it? If not, please inform me. I will do it. I think it is a necessary feature.
