### ISSUE TITLE
Set different dates to end and start tab

### ISSUE THREAD

**Issue by figus1909** [borax12/MaterialDateRangePicker#27]
Is there a possiblity to set different default dates to end and start date. I want date picker to open with different start and end dates.

**Comment by csbenz** [comment]
I want this too and it doesn't seem possible... a bit silly

**Comment by csbenz** [comment]
Pull Request #17 solves the problem, maybe we can complete the pull request! Will look into it tomorrow if I find the time.

**Comment by heysupratim** [comment]
@figus1909 @csbenz - i am merging the changes today . So thanks for reporting these issues and i hope the next version solves your issue

**Comment by csbenz** [comment]
@borax12 Thanks :)
