### ISSUE TITLE
Weird characters at end of TextView

### ISSUE THREAD

**Issue by csbenz** [borax12/MaterialDateRangePicker#28]
See [this image](https://dl2.pushbulletusercontent.com/68aDbVvH5FxWnpcXPumwDDv5yw7Zx6qc/Screenshot_20160301-165635.png).
On the "From" tab, I have additional characters that shouldn't be there.
The "To" tab is fine.

**Comment by heysupratim** [comment]
@csbenz Can you elaborate when exactly is this happening ?

**Comment by csbenz** [comment]
It's always there.  I'm calling it with:

``` java
TimePickerDialog timePickerDialog = TimePickerDialog.newInstance(MyFragment.this, 10, 15, false);
timePickerDialog.setAccentColor(ContextCompat.getColor(getActivity(), R.color.accent));
timePickerDialog.show(getActivity().getFragmentManager(), "TimePickerDialogTag");
```

**Comment by IzabellaMConigliaro** [comment]
Getting the same issue here. Any update?

**Comment by heysupratim** [comment]
@IzabellaMConigliaro @csbenz are you still getting the issue ? Can you please share the layout bound image with me
