### ISSUE TITLE
Translate texts

### ISSUE THREAD

**Issue by lucas-marciano** [borax12/MaterialDateRangePicker#30]
Hi, 

How can I change the language of the texts to pt-br, for example?

**Comment by heysupratim** [comment]
@lucas-marciano  You will have to add the translated strings the corresponding resource qualifier folders . values-pt-br in your case. I would be glad if you could translate the strings to your language of choice . I will merge it for the community's good

**Comment by lucas-marciano** [comment]
Tks man, i do it.

**Comment by deshario** [comment]
@lucas-marciano Did u do it ? Can i have look (example) that how did you use your own language! Thankx

**Comment by lucas-marciano** [comment]
@deshario I overwritten the library strings inside in my own string.xml file, see in the code what are the names.
