### ISSUE TITLE
Crash on android 4.4.2

### ISSUE THREAD

**Issue by murithi-evans** [borax12/MaterialDateRangePicker#31]
Hey,
I'm getting this error on android 4.4.2 devices
`java.lang.RuntimeException: Unable to start activity ComponentInfo{package/package.MainActivity}: android.view.InflateException: Binary XML file line #26: Error inflating class Button`.
It works fine on other devices

**Comment by heysupratim** [comment]
@murithi-evans ? Is this still happening ?
