### ISSUE TITLE
How can we change tabs green indicator color to something else (time picker)?

### ISSUE THREAD

**Issue by artests87** [borax12/MaterialDateRangePicker#32]
Hi!
We can't change tabs green indicator color to something else (time picker).
Meanwhile we can change tabs  indicator color to something else (date picker).
Thanks.

**Comment by artests87** [comment]
Maybe you would make all color indicators changeable for users?
For you it just some minutes work...

**Comment by heysupratim** [comment]
Custom color through and through is being added as top priority now
