### ISSUE TITLE
End time for new instance TimePickerDialog

### ISSUE THREAD

**Issue by artests87** [borax12/MaterialDateRangePicker#33]
Maybe you would make and "end time" in newInstance TimePickerDialog?

**Comment by csbenz** [comment]
+1
It was recently done for the Date picker, it should be easy to implement it for the Time picker.

**Comment by csbenz** [comment]
See #37

**Comment by csbenz** [comment]
Any update about this?

**Comment by csbenz** [comment]
Maybe it's easier to simply create a method "setEndTime" like the one that already exists for :
public void setStartTime(int hourOfDay, int minute)
