### ISSUE TITLE
How to detect user tap FROM/TO

### ISSUE THREAD

**Issue by CyberMew** [borax12/MaterialDateRangePicker#36]
Is there a way for us to know if user tap From/To?

Also, can we automatically jump to To when user has selected a date on From?

I would also like to highlight the selected range of dates, how is that possible?

It also looks like we can't detect date change?

**Comment by heysupratim** [comment]
@CyberMew Date change callback had an issue , it is fixed now , version 1.9 will have that working . highlight selected days is also added now
