### ISSUE TITLE
In "To" date calendar How to show selected date  according to "From" date calendar 

### ISSUE THREAD

**Issue by bschouhan19** [borax12/MaterialDateRangePicker#38]
Hello,
i am developing an app with range calendar  its awesome and helpful.
i have a problem, 
i want that if user select a date from first calendar  ("FROM calendar" )
then in second calendar ("To calendar")  that date show selected so that user can select relative date from first calendar 
please add a listener or method for that 

please help 
Thanks in advance

**Comment by heysupratim** [comment]
A new method has been added to the code that will be released in 1.9 that shows the higlighted days , that will solve your problem
