### ISSUE TITLE
Gradle Error:Could not find com.borax12.materialdaterangepicker:library:1.8.

### ISSUE THREAD

**Issue by leoliudeprecated** [borax12/MaterialDateRangePicker#44]
Gradle Error:Could not find com.borax12.materialdaterangepicker:library:1.8.

http://gradleplease.appspot.com/#borax12
https://bintray.com/search?query=borax12

Anyone knows how to include this library?

**Comment by leoliudeprecated** [comment]
This works though.
compile 'com.borax12.materialdaterangepicker:library:1.6

**Comment by ashif-ismail** [comment]
same error happens to me..

**Comment by Kamil-Kaminski** [comment]
I have the same problem, I can't download 1.8 version. Last working version is 1.7.
@borax12 Could you investigate the issue?

**Comment by ghost** [comment]
Check out my comment in another issue. https://github.com/borax12/MaterialDateRangePicker/issues/50#issuecomment-247498454

**Comment by heysupratim** [comment]
The jar is not included somehow in the 1.8 version , you will have to use the aar binary . I will be making sure the 1.9 version gets released in jar too
