### ISSUE TITLE
Issue in displaying pickerdailog in fragment

### ISSUE THREAD

**Issue by ashif-ismail** [borax12/MaterialDateRangePicker#46]
hello,i have tried this code
 `Calendar now = Calendar.getInstance();
DatePickerDialog dpd = DatePickerDialog.newInstance(
  MainActivity.this,
  now.get(Calendar.YEAR),
  now.get(Calendar.MONTH),
  now.get(Calendar.DAY_OF_MONTH)
);
dpd.show(getFragmentManager(), "Datepickerdialog");` 
in my fragment,since we need to change the context where in the above code passes MainActivity.this,i also tried with this code.
`Calendar now = Calendar.getInstance();
                DatePickerDialog dpd = new DatePickerDialog();
                dpd.show(getFragmentManager(), "Datepickerdialog");`
this code displays the dailog but its interface doesnt get called when picking a date range

i have also tried passing getActivty() and getContecxt() but none works,please help

**Comment by ashif-ismail** [comment]
voila it simply worked by using this code 
`Calendar now = Calendar.getInstance();
                DatePickerDialog dpd = DatePickerDialog.newInstance(
                        nameOfMyFragment.this,
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH)
                );
                dpd.show(getFragmentManager(), "Datepickerdialog");
            }`

**Comment by edwinmugendi** [comment]
Ensure your Fragment Class implements DatePickerDialog.OnDateSetListener
eg 

`public class DashboardFragment extends Fragment implements DatePickerDialog.OnDateSetListener {`
