### ISSUE TITLE
Disable To older than From

### ISSUE THREAD

**Issue by mtrakal** [borax12/MaterialDateRangePicker#5]
Hello,

is possible to disable days on To view which are older than From selected day by dialog settings?

I can calculate it manually and show Toast, but I didn't found any solution, how to cancel dismissing dialog after OK clicked.
I check setOnDismissListener which dismiss dialog, but I'm not able to stop dialog dismissing.

**Comment by heysupratim** [comment]
@mtrakal It is possible , but i am keeping it simple as of now, keeping these logics separate from the library , pertaining to users use case is better i think
