### ISSUE TITLE
Date picker To jump back after click on day

### ISSUE THREAD

**Issue by mtrakal** [borax12/MaterialDateRangePicker#6]
Date picker on To card jump back on current month after select some day in onother month/year than is current.
- select some day in FROM card
- swipe to next month
- click on some day
- ! calendar jump back on actual month selected in FROM card.

The behavior on FROM and TO cards is different.
Tested on Android 5.0

**Comment by seanhouli** [comment]
I am affected by this odd behavior as well. It is very jarring. An update to fix this ASAP would be greatly appreciated.

**Comment by heysupratim** [comment]
@mtrakal @seanhouli - sorry for the delay , working on the fix tonight . Will be up with other awesome bug fixes

**Comment by samnab** [comment]
New to android so IDK if I'm missing something obvious but I'm getting a NoSuchFieldError and is pointing to R.id.tabHost, R.id.start_date_group and R.id.end_date_group for both the time and date picker dialogs. Any help would help me alot. Thanks

**Comment by heysupratim** [comment]
@samnab in v1.3 you wont find the fix - fixed it :)

**Comment by heysupratim** [comment]
@mtrakal @seanhouli . I am trying but cant reproduce the case. Do i also need to select the day and press ok .

**Comment by Sharj** [comment]
I can reproduce the case as well on Android 5.1 - Nexus 4.

You don't have to press ok.

If `To` and `From` months are not the same, then in `To` view when you tap on a date, it's changed in the header but month view is moved to `From` month.

**Comment by heysupratim** [comment]
@sharj - yeah i think i got the issue. Well be checking it out. If in the mean time you find the solution. Submit a pr

**Comment by heysupratim** [comment]
@Sharj - fixed this , check in 1.6
