### ISSUE TITLE
How to I change the text colour of the Tabs - FROM and TO? 

### ISSUE THREAD

**Issue by georgikoemdzhiev** [borax12/MaterialDateRangePicker#66]
HI! First of all, thank you for the awesome library. It is very easy to use. I just have one question. How to change the colour of the two tabs at the top of the picker (TimePickerDialog more specificly). Currently, it looks like that: 

![device-2017-02-27-123444](https://cloud.githubusercontent.com/assets/11027608/23361561/30d81680-fce9-11e6-80f5-ed723ecefc3e.png)

Thank you in advance!

**Comment by benznest** [comment]
+1 I have the problem too.

**Comment by Rouix** [comment]
@georgikoemdzhiev Have you solved the problem?) If so, how?)

**Comment by GuoZhaoHui628** [comment]
+1 i have the same problem,  if you haved fix this  please  show

**Comment by GuoZhaoHui628** [comment]
o  I solved the problem , change app module styles.xml 
```
  <style name="AppTheme" parent="Theme.AppCompat">
 </style>
```
To 
```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
</style>
```·

**Comment by OmarMohamedDev** [comment]
If you don't want to change the whole app/activity theme, change just the style of the Dialog as was made here more in general (DatePickerDialog extends DialogFragment):https://stackoverflow.com/questions/15007272/how-to-change-the-background-color-around-a-dialogfragment
