### ISSUE TITLE
How to enable dates based on the from date

### ISSUE THREAD

**Issue by chakradhar451** [borax12/MaterialDateRangePicker#68]
Hi I want to disable in TO tab, all the dates before the date selected in FROM tab. Let me know how can I achieve this feature

**Comment by chakradhar451** [comment]
Why there is no reply yet from the developers...

**Comment by Abdelkader90** [comment]
hey did you find a solution for this ?

**Comment by neri4488** [comment]
Hello, did you find the solution for this, I don't want to select backward dates in TO field depending on FROM date.

**Comment by faeezmuhammed** [comment]
please respond developerss!!!!

**Comment by heysupratim** [comment]
This has been refererenced in issue #48 . Will be closing this to keep that issue alive and issue will be fixed in upcoming 2.1 release
