### ISSUE TITLE
Own Language Format

### ISSUE THREAD

**Issue by deshario** [borax12/MaterialDateRangePicker#75]
How can i use my own language with this lib ... Is there any example

**Comment by lutvie72** [comment]
can not, this is still under development and I plan to update the code. so anyone can easily develop it like adding language.

**Comment by parzibyte** [comment]
What do you mean? if you want to change "From" and "To" just call setStartTitle and setEndTitle:

```java
dpd.setStartTitle("Desde")
dpd.setEndTitle("Hasta")
```

**Comment by heysupratim** [comment]
Please add a translation PR if you think you want to add language support
