### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by MeinLieberScholli** [borax12/MaterialDateRangePicker#8]
i implemented the sample code, but got the following error:

java.lang.NoSuchFieldError: com.borax12.materialdaterangepicker.R$id.tabHost at com.borax12.materialdaterangepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:281)

**Comment by samoremec** [comment]
It's a problem if you're also using the com.wdullaer:materialdatetimepicker library.
Did you by any chance find a workaround?

**Comment by MeinLieberScholli** [comment]
Ah, thanks. I will try to find a workaround.

**Comment by csbenz** [comment]
Did you update this on jcenter repo? I still have the same problem using the two libraries. Thanks.

**Comment by csbenz** [comment]
I can see a version 1.3 [here](https://bintray.com/borax12/maven/material-datetime-rangepicker/1.3/view), but when I try and compile with 1.3 in android studio, it cannot find it.
Any help?

**Comment by heysupratim** [comment]
@csbenz did you try clearing /invalidating cache and then syncing the project again ?

**Comment by csbenz** [comment]
@borax12 Didn't work either. But I saw you updated the readme and it noe works with 1.5.
Thank you!

**Comment by heysupratim** [comment]
Always there for my users
