### ISSUE TITLE
Automatic maxDate tab FROM and minDate tab TO

### ISSUE THREAD

**Issue by hodangquocdat** [borax12/MaterialDateRangePicker#90]
Can we make the selector to automatically minDate in tab "**TO**" from the "**FROM**" tab to the "**TO**" and maxDate in tab "**FROM**" from the "**TO**" tab to "**FROM**"?

**Comment by faeezmuhammed** [comment]
did you get any solution for this?

**Comment by heysupratim** [comment]
This is a very niche use case and I would suggest building upon the existing lib to allow for this use case
